[package]
name = "auto-test"
version = "0.1.0"
authors = ["Nima-Rahimi-Foroushaani <nimacodecont@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
